#include "strings.hpp"

#include "config/config.hpp"

#include <tsl_utils.hpp>

#include <array>
#include <cstdio>
#include <cstring>

namespace i18n {

namespace {

char g_lang[8] = {};

struct Pair {
    const char *en;
    const char *ru;
};

// Indexed by underlying Str value — keep order identical to enum class Str.
// Count_ is a sentinel; it is NOT a row in this table.
constexpr std::array<Pair, static_cast<std::size_t>(Str::Count_)> kPairs = {{
    {"Player", "Плеер"},
    {"Settings", "Настройки"},
    {"Playlist", "Плейлист"},
    {"Browse", "Обзор"},
    {"Music Library", "Медиатека"},
    {"Volume", "Громкость"},
    {"Toggle Mute", "Без звука"},
    {"Music", "Музыка"},
    {"Game", "Игра"},
    {"Title ID", "Title ID"},
    {"Preset Volume", "Пресет громкости"},
    {"Default Focus", "Фокус по умолчанию"},
    {"Custom Focus", "Свой фокус"},
    {"Title Focus", "Фокус игры"},
    {"Home Focus", "Фокус HOME"},
    {"Miscellaneous", "Разное"},
    {"Playback Mode", "Режим воспроизведения"},
    {"Normal", "Обычный"},
    {"Whitelist", "Белый список"},
    {"Blacklist", "Чёрный список"},
    {"Whitelist", "Белый список"},
    {"Blacklist", "Чёрный список"},
    {"Language", "Язык"},
    {"Startup Settings", "Настройки запуска"},
    {"Auto-play Startup", "Автовоспроизведение при запуске"},
    {"Wait For Home", "Ждать HOME"},
    {"Pause On Keyboard", "Пауза на клавиатуре"},
    {"Pause On Controller Sync", "Пауза при синхронизации контроллера"},
    {"Pause On Lockscreen", "Пауза на локскрине"},
    {"Remove Startup", "Сбросить автозапуск"},
    {"Stop DferTune", "Остановить DferTune"},
    {"On", "Вкл"},
    {"Off", "Выкл"},
    {"Pass", "Нет"},
    {"Play", "Играть"},
    {"Pause", "Пауза"},
    {"Language", "Язык"},
    {"Empty...", "Пусто..."},
    {"Tracks", "Треки"},
    {"Playlist", "Плейлист"},
    {"Playlist is empty!", "Плейлист пуст!"},
    {"Couldn't open: ", "Не удалось открыть: "},
    {"Add To Playlist", "В плейлист"},
    {"Add All", "Добавить все"},
    {"Set As Startup", "Автозапуск"},
    {"Stopped Scanning Folder", "Сканирование остановлено"},
    {"Too many entries in folder.", "Слишком много элементов в папке."},
    {"Failed to switch to folder.", "Не удалось переключить папку."},
    {"Added 1 track to Playlist.", "Добавлен 1 трек в плейлист."},
    {"Failed to add track.", "Не удалось добавить трек."},
    {"Startup File Set", "Файл автозапуска задан"},
    {"Startup Folder Set", "Папка автозапуска задана"},
    {"Startup Path Removed", "Путь автозапуска сброшен"},
    {"No startup path set in config.", "Путь не задан"},
    {"Something went wrong.", "Что-то пошло не так."},
    {"Unknown Artist", "Неизвестный исполнитель"},
    {"Language changed", "Язык изменён"},
    {"Open Browse and add tracks here.", "Откройте «Обзор» и добавьте треки сюда."},
    {"Y remove · X clear · − startup", "Y — убрать · X — всё · − автозапуск"},
    {"Press + within a few seconds to undo.", "Нажмите + в течение нескольких секунд для отмены."},
    {"Track restored to playlist.", "Трек возвращён в плейлист."},
    {"Tip: Settings has playback modes, Home Focus, and language.", "Подсказка: в «Настройках» — режимы, фокус HOME и язык."},
    {" by ", " — "},
    {"Added %lld tracks to Playlist.", "Добавлено %lld треков в плейлист."},
    {"1 track", "1 трек"},
    {"%u tracks", "%u треков"},
    {"Shuffle", "Случайно"},
    {"Previous", "Назад"},
    {"Next", "Далее"},
    {"Repeat", "Повтор"},
    {"Select", "Выбрать"},
    {"Back", "Назад"},
    {"Selected", "Выбрано"},
    {"Remove", "Удалить"},
    {"Remove All", "Очистить все"},
}};


struct LocaleTable {
    const char *code;
    const std::array<const char *, static_cast<std::size_t>(Str::Count_)> &strings;
};

constexpr std::array<const char *, static_cast<std::size_t>(Str::Count_)> kDe = {{
    "Spieler",
    "Einstellungen",
    "Wiedergabeliste",
    "Durchsuchen",
    "Musikbibliothek",
    "Lautstärke",
    "Stummschalten umschalten",
    "Musik",
    "Spiel",
    "Titel-ID",
    "Preset-Lautstärke",
    "Standard-Fokus",
    "Eigener Fokus",
    "Titel-Fokus",
    "HOME-Fokus",
    "Sonstiges",
    "Wiedergabemodus",
    "Normal",
    "Whitelist",
    "Blacklist",
    "Whitelist",
    "Blacklist",
    "Sprache",
    "Starteinstellungen",
    "Autostart-Wiedergabe",
    "Auf HOME warten",
    "Bei Bildschirmtastatur pausieren",
    "Bei Controller-Synchronisierung pausieren",
    "Am Sperrbildschirm pausieren",
    "Autostart entfernen",
    "DferTune stoppen",
    "Ein",
    "Aus",
    "Ignorieren",
    "Wiedergabe",
    "Pause",
    "Sprache",
    "Leer...",
    "Titel",
    "Wiedergabeliste",
    "Playlist ist leer!",
    "Konnte nicht öffnen: ",
    "Zur Playlist hinzufügen",
    "Alle hinzufügen",
    "Als Autostart setzen",
    "Ordnerscan gestoppt",
    "Zu viele Einträge im Ordner.",
    "Ordnerwechsel fehlgeschlagen.",
    "1 Titel zur Playlist hinzugefügt.",
    "Titel konnte nicht hinzugefügt werden.",
    "Autostart-Datei gesetzt",
    "Autostart-Ordner gesetzt",
    "Autostart-Pfad entfernt",
    "Kein Autostart-Pfad gesetzt",
    "Etwas ist schiefgelaufen.",
    "Unbekannter Künstler",
    "Sprache geändert",
    "„Durchsuchen\" öffnen und Titel hinzufügen.",
    "Y entfernen · X leeren · − Autostart",
    "+ drücken zum Rückgängig machen.",
    "Titel zur Playlist wiederhergestellt.",
    "Tipp: Einstellungen enthält Wiedergabemodi, HOME-Fokus und Sprache.",
    " von ",
    "%lld Titel zur Playlist hinzugefügt.",
    "1 Titel",
    "%u Titel",
    "Zufall",
    "Zurück",
    "Weiter",
    "Wiederholen",
    "Wählen",
    "Zurück",
    "Ausgewählt",
    "Entfernen",
    "Alle entfernen",
}};

constexpr std::array<const char *, static_cast<std::size_t>(Str::Count_)> kEs = {{
    "Reproductor",
    "Ajustes",
    "Lista",
    "Explorar",
    "Biblioteca musical",
    "Volumen",
    "Alternar silencio",
    "Música",
    "Juego",
    "ID del título",
    "Volumen predefinido",
    "Foco predeterminado",
    "Foco personalizado",
    "Foco del juego",
    "Foco de HOME",
    "Varios",
    "Modo de reproducción",
    "Normal",
    "Lista blanca",
    "Lista negra",
    "Lista blanca",
    "Lista negra",
    "Idioma",
    "Ajustes de inicio",
    "Reproducir al iniciar",
    "Esperar a HOME",
    "Pausar con el teclado",
    "Pausar durante la sincronización del mando",
    "Pausar en pantalla de bloqueo",
    "Quitar inicio",
    "Detener DferTune",
    "Sí",
    "No",
    "Omitir",
    "Reproducir",
    "Pausar",
    "Idioma",
    "Vacío...",
    "Pistas",
    "Lista",
    "¡La lista está vacía!",
    "No se pudo abrir: ",
    "Añadir a la lista",
    "Añadir todo",
    "Definir como inicio",
    "Escaneo detenido",
    "Demasiadas entradas en la carpeta.",
    "No se pudo cambiar de carpeta.",
    "1 pista añadida a la lista.",
    "No se pudo añadir la pista.",
    "Archivo de inicio definido",
    "Carpeta de inicio definida",
    "Ruta de inicio eliminada",
    "No hay ruta de inicio",
    "Algo salió mal.",
    "Artista desconocido",
    "Idioma cambiado",
    "Abre Explorar y añade pistas aquí.",
    "Y eliminar · X limpiar · − inicio",
    "Pulsa + en pocos segundos para deshacer.",
    "Pista restaurada a la lista.",
    "Consejo: Ajustes tiene modos de reproducción, Foco HOME e idioma.",
    " de ",
    "%lld pistas añadidas a la lista.",
    "1 pista",
    "%u pistas",
    "Aleatorio",
    "Anterior",
    "Siguiente",
    "Repetir",
    "Seleccionar",
    "Atrás",
    "Seleccionado",
    "Eliminar",
    "Eliminar todo",
}};

constexpr std::array<const char *, static_cast<std::size_t>(Str::Count_)> kFr = {{
    "Lecteur",
    "Paramètres",
    "Liste de lecture",
    "Parcourir",
    "Bibliothèque musicale",
    "Volume sonore",
    "Basculer muet",
    "Musique",
    "Jeu",
    "ID du titre",
    "Volume prédéfini",
    "Focus par défaut",
    "Focus personnalisé",
    "Focus du jeu",
    "Focus HOME",
    "Divers",
    "Mode de lecture",
    "Normal",
    "Liste blanche",
    "Liste noire",
    "Liste blanche",
    "Liste noire",
    "Langue",
    "Paramètres de démarrage",
    "Lecture au démarrage",
    "Attendre HOME",
    "Mettre en pause avec le clavier",
    "Mettre en pause pendant la synchronisation de la manette",
    "Mettre en pause à l’écran verrouillé",
    "Retirer le démarrage",
    "Arrêter DferTune",
    "Activé",
    "Désactivé",
    "Ignorer",
    "Lecture",
    "Pause",
    "Langue",
    "Vide...",
    "Morceaux",
    "Liste de lecture",
    "La playlist est vide !",
    "Impossible d'ouvrir : ",
    "Ajouter à la playlist",
    "Tout ajouter",
    "Définir au démarrage",
    "Analyse du dossier arrêtée",
    "Trop d'entrées dans le dossier.",
    "Impossible de changer de dossier.",
    "1 piste ajoutée à la liste.",
    "Impossible d'ajouter la piste.",
    "Fichier de démarrage défini",
    "Dossier de démarrage défini",
    "Chemin de démarrage retiré",
    "Aucun chemin de démarrage",
    "Une erreur s'est produite.",
    "Artiste inconnu",
    "Langue modifiée",
    "Ouvrez Parcourir et ajoutez des pistes ici.",
    "Y supprimer · X vider · − démarrage",
    "Appuyez sur + en quelques secondes pour annuler.",
    "Piste restaurée dans la liste.",
    "Astuce : Paramètres contient les modes de lecture, Focus HOME et la langue.",
    " par ",
    "%lld pistes ajoutées à la liste.",
    "1 morceau",
    "%u pistes",
    "Aléatoire",
    "Précédent",
    "Suivant",
    "Répéter",
    "Sélectionner",
    "Retour",
    "Sélectionné",
    "Retirer",
    "Tout retirer",
}};

constexpr std::array<const char *, static_cast<std::size_t>(Str::Count_)> kIt = {{
    "Lettore",
    "Impostazioni",
    "Playlist musicale",
    "Sfoglia",
    "Libreria musicale",
    "Volume audio",
    "Attiva/disattiva muto",
    "Musica",
    "Gioco",
    "ID titolo",
    "Volume predefinito",
    "Focus predefinito",
    "Focus personalizzato",
    "Focus gioco",
    "Focus HOME",
    "Varie",
    "Modalità di riproduzione",
    "Normale",
    "Lista consentiti",
    "Lista bloccati",
    "Lista consentiti",
    "Lista bloccati",
    "Lingua",
    "Impostazioni di avvio",
    "Riproduci all'avvio",
    "Attendi HOME",
    "Pausa con la tastiera",
    "Pausa durante la sincronizzazione del controller",
    "Pausa nella schermata di blocco",
    "Rimuovi avvio",
    "Ferma DferTune",
    "On",
    "Off",
    "Ignora",
    "Riproduci",
    "Pausa",
    "Lingua",
    "Vuoto...",
    "Brani",
    "Playlist musicale",
    "La playlist è vuota!",
    "Impossibile aprire: ",
    "Aggiungi alla playlist",
    "Aggiungi tutto",
    "Imposta all'avvio",
    "Scansione cartella interrotta",
    "Troppi elementi nella cartella.",
    "Impossibile cambiare cartella.",
    "1 brano aggiunto alla playlist.",
    "Impossibile aggiungere il brano.",
    "File di avvio impostato",
    "Cartella di avvio impostata",
    "Percorso di avvio rimosso",
    "Nessun percorso di avvio",
    "Qualcosa è andato storto.",
    "Artista sconosciuto",
    "Lingua cambiata",
    "Apri Sfoglia e aggiungi brani qui.",
    "Y rimuovi · X svuota · − avvio",
    "Premi + entro pochi secondi per annullare.",
    "Brano ripristinato nella playlist.",
    "Suggerimento: Impostazioni ha modalità di riproduzione, Focus HOME e lingua.",
    " di ",
    "%lld brani aggiunti alla playlist.",
    "1 brano",
    "%u brani",
    "Casuale",
    "Precedente",
    "Successivo",
    "Ripeti",
    "Seleziona",
    "Indietro",
    "Selezionato",
    "Rimuovi",
    "Rimuovi tutto",
}};

constexpr std::array<const char *, static_cast<std::size_t>(Str::Count_)> kJa = {{
    "プレーヤー",
    "設定",
    "プレイリスト",
    "参照",
    "音楽ライブラリ",
    "音量",
    "ミュート切替",
    "音楽",
    "ゲーム",
    "タイトルID",
    "プリセット音量",
    "既定フォーカス",
    "カスタムフォーカス",
    "ゲームフォーカス",
    "HOMEフォーカス",
    "その他",
    "再生モード",
    "通常",
    "ホワイトリスト",
    "ブラックリスト",
    "ホワイトリスト",
    "ブラックリスト",
    "言語",
    "起動設定",
    "起動時に再生",
    "HOMEまで待機",
    "キーボードで一時停止",
    "コントローラー同期中に一時停止",
    "ロック画面で一時停止",
    "起動設定を削除",
    "DferTuneを停止",
    "オン",
    "オフ",
    "何もしない",
    "再生",
    "一時停止",
    "言語",
    "空...",
    "トラック",
    "プレイリスト",
    "プレイリストは空です!",
    "開けません: ",
    "プレイリストに追加",
    "すべて追加",
    "起動時に設定",
    "フォルダスキャン停止",
    "フォルダ内のエントリが多すぎます。",
    "フォルダの切り替えに失敗しました。",
    "プレイリストに1曲追加しました。",
    "トラックの追加に失敗しました。",
    "起動ファイルを設定",
    "起動フォルダを設定",
    "起動パスを削除しました",
    "起動パス未設定",
    "問題が発生しました。",
    "不明なアーティスト",
    "言語が変更されました",
    "ブラウズを開いてトラックを追加してください。",
    "Y 削除 · X クリア · − 起動",
    "数秒以内に + を押して元に戻す。",
    "トラックをプレイリストに復元しました。",
    "ヒント: 設定には再生モード、HOMEフォーカス、言語があります。",
    " - ",
    "プレイリストに%lld曲追加しました。",
    "1曲",
    "%u曲",
    "シャッフル",
    "前へ",
    "次へ",
    "リピート",
    "選択",
    "戻る",
    "選択済み",
    "削除",
    "すべて削除",
}};

constexpr std::array<const char *, static_cast<std::size_t>(Str::Count_)> kKo = {{
    "플레이어",
    "설정",
    "재생 목록",
    "찾아보기",
    "음악 라이브러리",
    "볼륨",
    "음소거 전환",
    "음악",
    "게임",
    "타이틀 ID",
    "프리셋 볼륨",
    "기본 포커스",
    "사용자 포커스",
    "게임 포커스",
    "HOME 포커스",
    "기타",
    "재생 모드",
    "일반",
    "허용 목록",
    "차단 목록",
    "허용 목록",
    "차단 목록",
    "언어",
    "시작 설정",
    "시작 시 자동 재생",
    "HOME까지 대기",
    "키보드에서 일시 정지",
    "컨트롤러 동기화 중 일시 정지",
    "잠금 화면에서 일시 정지",
    "시작 항목 제거",
    "DferTune 중지",
    "켜짐",
    "꺼짐",
    "통과",
    "재생",
    "일시정지",
    "언어",
    "비어 있음...",
    "트랙",
    "재생 목록",
    "재생 목록이 비어 있습니다!",
    "열 수 없음: ",
    "재생 목록에 추가",
    "모두 추가",
    "시작으로 설정",
    "폴더 검색 중지",
    "폴더에 항목이 너무 많습니다.",
    "폴더 전환에 실패했습니다.",
    "재생목록에 1곡 추가됨.",
    "트랙 추가에 실패했습니다.",
    "시작 파일 설정됨",
    "시작 폴더 설정됨",
    "시작 경로 제거됨",
    "시작 경로 없음",
    "문제가 발생했습니다.",
    "알 수 없는 아티스트",
    "언어가 변경되었습니다",
    "탐색을 열고 트랙을 추가하세요.",
    "Y 제거 · X 지우기 · − 시작",
    "몇 초 안에 +를 눌러 실행 취소.",
    "트랙이 재생목록에 복원됨.",
    "팁: 설정에는 재생 모드, HOME 포커스, 언어가 있습니다.",
    " - ",
    "재생목록에 %lld곡 추가됨.",
    "1곡",
    "%u곡",
    "셔플",
    "이전",
    "다음",
    "반복",
    "선택",
    "뒤로",
    "선택됨",
    "제거",
    "모두 제거",
}};

constexpr std::array<const char *, static_cast<std::size_t>(Str::Count_)> kNl = {{
    "Speler",
    "Instellingen",
    "Afspeellijst",
    "Bladeren",
    "Muziekbibliotheek",
    "Geluidsvolume",
    "Dempen wisselen",
    "Muziek",
    "Game",
    "Titel-ID",
    "Preset-volume",
    "Standaardfocus",
    "Eigen focus",
    "Gamefocus",
    "HOME-focus",
    "Overig",
    "Afspeelmodus",
    "Normaal",
    "Whitelist",
    "Blacklist",
    "Whitelist",
    "Blacklist",
    "Taal",
    "Opstartinstellingen",
    "Automatisch afspelen",
    "Wachten op HOME",
    "Pauzeren bij toetsenbord",
    "Pauzeren bij controllersynchronisatie",
    "Pauzeren op vergrendelscherm",
    "Opstart verwijderen",
    "DferTune stoppen",
    "Aan",
    "Uit",
    "Overslaan",
    "Afspelen",
    "Pauze",
    "Taal",
    "Leeg...",
    "Nummers",
    "Afspeellijst",
    "Afspeellijst is leeg!",
    "Kon niet openen: ",
    "Aan afspeellijst toevoegen",
    "Alles toevoegen",
    "Instellen als opstart",
    "Mapscan gestopt",
    "Te veel items in de map.",
    "Kon niet wisselen van map.",
    "1 nummer toegevoegd aan afspeellijst.",
    "Nummer kon niet worden toegevoegd.",
    "Opstartbestand ingesteld",
    "Opstartmap ingesteld",
    "Opstartpad verwijderd",
    "Geen opstartpad ingesteld",
    "Er is iets misgegaan.",
    "Onbekende artiest",
    "Taal gewijzigd",
    "Open Bladeren en voeg nummers toe.",
    "Y verwijderen · X wissen · − opstarten",
    "Druk binnen enkele seconden op + om ongedaan te maken.",
    "Nummer hersteld in afspeellijst.",
    "Tip: Instellingen heeft afspeelmodi, HOME-focus en taal.",
    " van ",
    "%lld nummers toegevoegd aan afspeellijst.",
    "1 nummer",
    "%u nummers",
    "Willekeurig",
    "Vorige",
    "Volgende",
    "Herhalen",
    "Kiezen",
    "Terug",
    "Geselecteerd",
    "Verwijderen",
    "Alles verwijderen",
}};

constexpr std::array<const char *, static_cast<std::size_t>(Str::Count_)> kPl = {{
    "Odtwarzacz",
    "Ustawienia",
    "Playlista",
    "Przeglądaj",
    "Biblioteka muzyki",
    "Głośność",
    "Przełącz wyciszenie",
    "Muzyka",
    "Gra",
    "ID tytułu",
    "Głośność preset",
    "Domyślny fokus",
    "Własny fokus",
    "Fokus gry",
    "Fokus HOME",
    "Różne",
    "Tryb odtwarzania",
    "Normalny",
    "Biała lista",
    "Czarna lista",
    "Biała lista",
    "Czarna lista",
    "Język",
    "Ustawienia uruchamiania",
    "Autoodtwarzanie przy starcie",
    "Czekaj na HOME",
    "Wstrzymaj przy klawiaturze",
    "Wstrzymaj podczas synchronizacji kontrolera",
    "Wstrzymaj na ekranie blokady",
    "Usuń start",
    "Zatrzymaj DferTune",
    "Wł.",
    "Wył.",
    "Pomiń",
    "Odtwarzaj",
    "Pauza",
    "Język",
    "Pusto...",
    "Utwory",
    "Playlista",
    "Playlista jest pusta!",
    "Nie można otworzyć: ",
    "Dodaj do playlisty",
    "Dodaj wszystko",
    "Ustaw jako start",
    "Skanowanie folderu zatrzymane",
    "Za dużo wpisów w folderze.",
    "Nie udało się przełączyć folderu.",
    "Dodano 1 utwór do playlisty.",
    "Nie udało się dodać utworu.",
    "Plik startowy ustawiony",
    "Folder startowy ustawiony",
    "Ścieżka startowa usunięta",
    "Brak ścieżki startowej",
    "Coś poszło nie tak.",
    "Nieznany artysta",
    "Język zmieniony",
    "Otwórz Przeglądaj i dodaj tutaj utwory.",
    "Y usuń · X wyczyść · − autostart",
    "Naciśnij + w ciągu kilku sekund, aby cofnąć.",
    "Utwór przywrócony do playlisty.",
    "Wskazówka: Ustawienia zawiera tryby odtwarzania, fokus HOME i język.",
    " - ",
    "Dodano %lld utworów do playlisty.",
    "1 utwór",
    "%u utworów",
    "Losowo",
    "Poprzedni",
    "Następny",
    "Powtórz",
    "Wybierz",
    "Wstecz",
    "Wybrano",
    "Usuń",
    "Usuń wszystko",
}};

constexpr std::array<const char *, static_cast<std::size_t>(Str::Count_)> kPt = {{
    "Reprodutor",
    "Configurações",
    "Lista de reprodução",
    "Navegar",
    "Biblioteca musical",
    "Volume de áudio",
    "Alternar mudo",
    "Música",
    "Jogo",
    "ID do título",
    "Volume predefinido",
    "Foco padrão",
    "Foco personalizado",
    "Foco do jogo",
    "Foco HOME",
    "Diversos",
    "Modo de reprodução",
    "Normal",
    "Lista branca",
    "Lista negra",
    "Lista branca",
    "Lista negra",
    "Idioma",
    "Configurações de inicialização",
    "Reproduzir ao iniciar",
    "Aguardar HOME",
    "Pausar com teclado",
    "Pausar durante a sincronização do controle",
    "Pausar na tela de bloqueio",
    "Remover inicialização",
    "Parar DferTune",
    "Ligado",
    "Desligado",
    "Ignorar",
    "Reproduzir",
    "Pausar",
    "Idioma",
    "Vazio...",
    "Faixas",
    "Lista de reprodução",
    "A playlist está vazia!",
    "Não foi possível abrir: ",
    "Adicionar à playlist",
    "Adicionar tudo",
    "Definir ao iniciar",
    "Varredura da pasta parada",
    "Entradas demais na pasta.",
    "Falha ao mudar de pasta.",
    "1 faixa adicionada à lista.",
    "Falha ao adicionar faixa.",
    "Arquivo de inicialização definido",
    "Pasta de inicialização definida",
    "Caminho de inicialização removido",
    "Nenhum caminho de inicialização",
    "Algo deu errado.",
    "Artista desconhecido",
    "Idioma alterado",
    "Abra Explorar e adicione faixas aqui.",
    "Y remover · X limpar · − inicialização",
    "Pressione + em poucos segundos para desfazer.",
    "Faixa restaurada na lista.",
    "Dica: Configurações tem modos de reprodução, Foco HOME e idioma.",
    " de ",
    "%lld faixas adicionadas à lista.",
    "1 faixa",
    "%u faixas",
    "Aleatório",
    "Anterior",
    "Próxima",
    "Repetir",
    "Selecionar",
    "Voltar",
    "Selecionado",
    "Remover",
    "Remover tudo",
}};

constexpr std::array<const char *, static_cast<std::size_t>(Str::Count_)> kUk = {{
    "Плеєр",
    "Опції",
    "Плейлист",
    "Огляд",
    "Медіатека",
    "Гучність",
    "Без звуку",
    "Музика",
    "Гра",
    "ID гри",
    "Пресет гучності",
    "Фокус за замовчуванням",
    "Свій фокус",
    "Фокус: гра",
    "Фокус: меню",
    "Інше",
    "Режим роботи",
    "Звичайний",
    "Білий список",
    "Чорний список",
    "Білий список",
    "Чорний список",
    "Мова",
    "Налаштування запуску",
    "Автозапуск",
    "Чекати HOME",
    "Пауза на клавіатурі",
    "Пауза під час синхронізації контролера",
    "Пауза на екрані блокування",
    "Видалити автозапуск",
    "Зупинити",
    "Увімк",
    "Вимк",
    "Пропустити",
    "Пуск",
    "Пауза",
    "Мова",
    "Порожньо",
    "Треки",
    "Плейлист",
    "Плейлист порожній",
    "Помилка відкриття: ",
    "У плейлист",
    "Додати все",
    "На автозапуск",
    "Сканування перервано",
    "Забагато записів у папці.",
    "Не вдалося перейти до папки.",
    "1 трек додано до плейлисту.",
    "Не вдалося додати трек.",
    "Файл автозапуску задано",
    "Папку автозапуску задано",
    "Шлях видалено",
    "Шлях не задано",
    "Щось пішло не так.",
    "Невідомий виконавець",
    "Мову змінено",
    "Відкрийте «Огляд» і додайте треки сюди.",
    "Y — видалити · X — очистити · − автозапуск",
    "Натисніть + протягом кількох секунд для скасування.",
    "Трек повернуто до плейлисту.",
    "Підказка: у «Налаштуваннях» — режими, фокус HOME та мова.",
    " - ",
    "Додано %lld треків до плейлисту.",
    "1 трек",
    "%u треків",
    "Випадково",
    "Назад",
    "Далі",
    "Повтор",
    "Вибрати",
    "Назад",
    "Вибрано",
    "Видалити",
    "Очистити все",
}};

constexpr std::array<const char *, static_cast<std::size_t>(Str::Count_)> kZh = {{
    "播放器",
    "设置",
    "播放列表",
    "浏览",
    "音乐库",
    "音量",
    "静音",
    "音乐",
    "游戏",
    "ID",
    "预设音量",
    "默认焦点",
    "自定义焦点",
    "游戏焦点",
    "主页焦点",
    "杂项",
    "播放模式",
    "普通",
    "白名单",
    "黑名单",
    "白名单",
    "黑名单",
    "语言",
    "启动设置",
    "开机启动",
    "等待 HOME",
    "键盘时暂停",
    "控制器同步时暂停",
    "锁屏时暂停",
    "移除启动",
    "停止",
    "开",
    "关",
    "跳过",
    "播放",
    "暂停",
    "语言",
    "空",
    "曲目",
    "播放列表",
    "列表为空",
    "打不开: ",
    "添加到列表",
    "添加全部",
    "设为启动",
    "扫描停止",
    "文件夹中条目过多。",
    "无法切换文件夹。",
    "已将1首歌曲添加到播放列表。",
    "添加曲目失败。",
    "启动文件已设",
    "启动文件夹已设",
    "路径已移除",
    "未设置路径",
    "出了点问题。",
    "未知艺术家",
    "语言已更改",
    "打开浏览并在此处添加曲目。",
    "Y 删除 · X 清空 · − 启动",
    "几秒内按 + 撤销。",
    "曲目已恢复到播放列表。",
    "提示：设置中有播放模式、主页焦点和语言。",
    " - ",
    "已将%lld首歌曲添加到播放列表。",
    "1 首",
    "%u首",
    "随机",
    "上一首",
    "下一首",
    "重复",
    "选择",
    "返回",
    "已选择",
    "移除",
    "全部移除",
}};

constexpr std::array<const char *, static_cast<std::size_t>(Str::Count_)> kZhCn = {{
    "播放器",
    "设置",
    "播放列表",
    "浏览",
    "音乐库",
    "音量",
    "静音",
    "音乐",
    "游戏",
    "ID",
    "预设音量",
    "默认焦点",
    "自定义焦点",
    "游戏焦点",
    "主页焦点",
    "杂项",
    "播放模式",
    "普通",
    "白名单",
    "黑名单",
    "白名单",
    "黑名单",
    "语言",
    "启动设置",
    "开机启动",
    "等待 HOME",
    "键盘时暂停",
    "控制器同步时暂停",
    "锁屏时暂停",
    "移除启动",
    "停止",
    "开",
    "关",
    "跳过",
    "播放",
    "暂停",
    "语言",
    "空",
    "曲目",
    "播放列表",
    "列表为空",
    "打不开: ",
    "添加到列表",
    "添加全部",
    "设为启动",
    "扫描停止",
    "文件夹中条目过多。",
    "无法切换文件夹。",
    "已将1首歌曲添加到播放列表。",
    "添加曲目失败。",
    "启动文件已设",
    "启动文件夹已设",
    "路径已移除",
    "未设置路径",
    "出了点问题。",
    "未知艺术家",
    "语言已更改",
    "打开浏览并在此处添加曲目。",
    "Y 删除 · X 清空 · − 启动",
    "几秒内按 + 撤销。",
    "曲目已恢复到播放列表。",
    "提示：设置中有播放模式、主页焦点和语言。",
    " - ",
    "已将%lld首歌曲添加到播放列表。",
    "1 首",
    "%u首",
    "随机",
    "上一首",
    "下一首",
    "重复",
    "选择",
    "返回",
    "已选择",
    "移除",
    "全部移除",
}};

constexpr std::array<const char *, static_cast<std::size_t>(Str::Count_)> kZhTw = {{
    "播放器",
    "設定",
    "播放列表",
    "瀏覽",
    "音樂庫",
    "音量",
    "靜音",
    "音樂",
    "遊戲",
    "ID",
    "預設音量",
    "預設焦點",
    "自訂焦點",
    "遊戲焦點",
    "主頁焦點",
    "雜項",
    "播放模式",
    "普通",
    "白名單",
    "黑名單",
    "白名單",
    "黑名單",
    "語言",
    "啟動設定",
    "開機啟動",
    "等待 HOME",
    "使用鍵盤時暫停",
    "控制器同步時暫停",
    "鎖定畫面時暫停",
    "移除啟動",
    "停止",
    "開",
    "關",
    "跳過",
    "播放",
    "暫停",
    "語言",
    "空",
    "曲目",
    "播放列表",
    "列表為空",
    "無法開啟: ",
    "新增到列表",
    "新增全部",
    "設為啟動",
    "掃描停止",
    "資料夾中的項目過多。",
    "無法切換資料夾。",
    "已將1首歌曲加入播放清單。",
    "新增曲目失敗。",
    "啟動檔案已設定",
    "啟動資料夾已設定",
    "路徑已移除",
    "未設定路徑",
    "發生了問題。",
    "未知藝術家",
    "語言已更改",
    "開啟瀏覽並在此新增曲目。",
    "Y 移除 · X 清空 · − 啟動",
    "幾秒內按 + 撤銷。",
    "曲目已恢復到播放清單。",
    "提示：設定中有播放模式、主頁焦點和語言。",
    " - ",
    "已將%lld首歌曲加入播放清單。",
    "1 首",
    "%u首",
    "隨機",
    "上一首",
    "下一首",
    "重複",
    "選擇",
    "返回",
    "已選擇",
    "移除",
    "全部移除",
}};

constexpr std::array<LocaleTable, 13> kLocaleTables = {{
    {"de", kDe},
    {"es", kEs},
    {"fr", kFr},
    {"it", kIt},
    {"ja", kJa},
    {"ko", kKo},
    {"nl", kNl},
    {"pl", kPl},
    {"pt", kPt},
    {"uk", kUk},
    {"zh", kZh},
    {"zh-cn", kZhCn},
    {"zh-tw", kZhTw}
}};

static_assert(kPairs.size() == static_cast<std::size_t>(Str::Count_),
              "kPairs size must match Str::Count_");

constexpr std::size_t idx(Str id) {
    return static_cast<std::size_t>(id);
}

bool isRussian() {
    return std::strcmp(g_lang, "ru") == 0;
}

const char *builtinTranslation(std::size_t i) {
    if (std::strcmp(g_lang, "en") == 0)
        return kPairs[i].en;
    if (std::strcmp(g_lang, "zh") == 0)
        return kZhCn[i];

    for (const auto &locale : kLocaleTables) {
        if (std::strcmp(g_lang, locale.code) == 0)
            return locale.strings[i];
    }
    return nullptr;
}

} // namespace

void syncFromConfig() {
    config::get_language(g_lang, sizeof(g_lang));
    if (g_lang[0] == '\0') {
        g_lang[0] = 'r';
        g_lang[1] = 'u';
        g_lang[2] = '\0';
    }
}

bool isRu() {
    return isRussian();
}

const char *t(Str id) {
    const auto i = idx(id);
    if (i >= kPairs.size())
        return "";

    // Every bundled language is loaded into this cache at startup and whenever
    // the language changes. It must be consulted first: otherwise a built-in
    // table silently masks new or corrected entries in overlay/lang/*.json.
    const char *en_key = kPairs[i].en;
    const auto it = ult::translationCache.find(en_key);
    if (it != ult::translationCache.end())
        return it->second.c_str();

    // The compiled tables remain a safe fallback for an incomplete custom
    // package or a missing translation file.
    if (isRussian())
        return kPairs[i].ru;
    if (const char *built_in = builtinTranslation(i))
        return built_in;
    return en_key;
}

const char *text(const char *englishKey) {
    if (!englishKey)
        return "";
    const auto it = ult::translationCache.find(englishKey);
    return it != ult::translationCache.end() ? it->second.c_str() : englishKey;
}

const char *trackCountLabel(std::uint32_t count) {
    static char buf[48];
    if (count == 1u) {
        if (auto it = ult::translationCache.find("ONE_TRACK"); it != ult::translationCache.end())
            return it->second.c_str();
        return t(Str::TrackCountOne);
    }
    if (isRussian()) {
        const unsigned n     = static_cast<unsigned>(count);
        const unsigned n10   = n % 10u;
        const unsigned n100  = n % 100u;
        const char *word     = "треков";
        if (n10 == 1u && n100 != 11u)
            word = "трек";
        else if (n10 >= 2u && n10 <= 4u && (n100 < 10u || n100 >= 20u))
            word = "трека";
        std::snprintf(buf, sizeof(buf), "%u %s", n, word);
    } else {
        if (auto it = ult::translationCache.find("N_TRACKS"); it != ult::translationCache.end()) {
            std::snprintf(buf, sizeof(buf), "%u%s", static_cast<unsigned>(count), it->second.c_str());
        } else {
            std::snprintf(buf, sizeof(buf), t(Str::TrackCountManyFmt), static_cast<unsigned>(count));
        }
    }
    return buf;
}

} // namespace i18n
